// Code generated by goyacc -o lib/filter/parser.go lib/filter/parser.y. DO NOT EDIT.

//line lib/filter/parser.y:2
package filter

import __yyfmt__ "fmt"

//line lib/filter/parser.y:2

import (
	"strings"
	"time"
)

//line lib/filter/parser.y:9
type yySymType struct {
	yys   int
	token Token
	expr  Expression
	exprs []Expression
}

const BY = 57346
const TO = 57347
const ADDED = 57348
const ASSIGNED = 57349
const SUBTASK = 57350
const SHARED = 57351
const STRING = 57352
const NUMBER = 57353
const NEXT = 57354
const MONTH_IDENT = 57355
const TWELVE_CLOCK_IDENT = 57356
const HOURS = 57357
const PRIORITY = 57358
const RECURRING = 57359
const TODAY_IDENT = 57360
const TOMORROW_IDENT = 57361
const YESTERDAY_IDENT = 57362
const DAYS = 57363
const VIEW = 57364
const ALL = 57365
const DUE = 57366
const CREATED = 57367
const BEFORE = 57368
const AFTER = 57369
const OVER = 57370
const OVERDUE = 57371
const NO = 57372
const DATE = 57373
const TIME = 57374
const LABELS = 57375
const SEARCH = 57376
const ORDINAL = 57377
const WEEKDAY = 57378
const YEAR_NUMBER = 57379
const AT = 57380
const P1 = 57381
const P2 = 57382
const P3 = 57383
const P4 = 57384

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BY",
	"TO",
	"ADDED",
	"ASSIGNED",
	"SUBTASK",
	"SHARED",
	"STRING",
	"NUMBER",
	"NEXT",
	"MONTH_IDENT",
	"TWELVE_CLOCK_IDENT",
	"HOURS",
	"PRIORITY",
	"RECURRING",
	"TODAY_IDENT",
	"TOMORROW_IDENT",
	"YESTERDAY_IDENT",
	"DAYS",
	"VIEW",
	"ALL",
	"DUE",
	"CREATED",
	"BEFORE",
	"AFTER",
	"OVER",
	"OVERDUE",
	"NO",
	"DATE",
	"TIME",
	"LABELS",
	"SEARCH",
	"ORDINAL",
	"WEEKDAY",
	"YEAR_NUMBER",
	"AT",
	"P1",
	"P2",
	"P3",
	"P4",
	"'#'",
	"'\\\\'",
	"'&'",
	"'*'",
	"'/'",
	"','",
	"'.'",
	"'|'",
	"'('",
	"')'",
	"'!'",
	"':'",
	"'-'",
	"'+'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line lib/filter/parser.y:432

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 180

var yyAct = [...]uint8{
	39, 82, 24, 25, 129, 112, 110, 36, 35, 45,
	58, 59, 60, 61, 47, 48, 49, 69, 71, 109,
	108, 106, 105, 89, 74, 3, 77, 93, 96, 53,
	56, 57, 95, 97, 98, 94, 87, 89, 55, 128,
	131, 78, 55, 54, 85, 70, 50, 54, 75, 102,
	130, 34, 50, 116, 75, 37, 119, 104, 118, 77,
	77, 77, 77, 88, 33, 68, 79, 120, 114, 67,
	86, 113, 132, 107, 117, 115, 92, 88, 111, 99,
	100, 101, 51, 91, 76, 103, 90, 52, 51, 51,
	76, 38, 84, 52, 52, 83, 80, 81, 73, 72,
	26, 10, 63, 9, 23, 8, 7, 121, 122, 123,
	66, 124, 77, 125, 126, 11, 127, 65, 62, 64,
	13, 32, 77, 46, 2, 1, 77, 77, 77, 31,
	20, 19, 18, 37, 36, 35, 45, 0, 0, 40,
	15, 47, 48, 49, 0, 14, 0, 17, 16, 0,
	0, 29, 30, 12, 0, 0, 0, 21, 0, 22,
	0, 28, 41, 42, 43, 44, 27, 51, 0, 38,
	6, 0, 52, 0, 4, 0, 5, 0, 34, 50,
}

var yyPact = [...]int16{
	123, -1000, -19, -7, 123, 123, 45, 45, 45, 45,
	-1000, -1000, 86, -1000, 46, -1000, 39, -9, -1000, -1000,
	94, -30, -1000, -1000, -1000, 44, -1000, -2, -1000, 42,
	-1000, 92, -10, -1000, 84, 81, 23, -1000, -1000, -1000,
	75, -1000, -1000, -1000, -1000, 72, -1000, -1000, -1000, -1000,
	65, -18, -1000, 123, 123, 123, -3, -1000, 44, 38,
	44, 44, -1000, -1000, -1000, -1000, 26, -1000, -32, -33,
	-4, -34, -35, -48, 45, -1000, -1000, -1000, -1000, -1000,
	-49, -1000, 9, 50, 47, -1000, 64, 16, 63, -1000,
	-1000, 21, 52, -1000, -1000, -1000, -1000, -1000, -1000, -7,
	-1000, -1000, -1000, 45, -1000, -4, -4, -1000, -4, 45,
	45, 44, 45, -1000, -1000, -8, -1000, -50, -1000, 13,
	-1000, 44, -1000, -1000, -1000, 44, 44, 44, 3, 61,
	-1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 125, 124, 25, 2, 123, 121, 120, 115, 106,
	105, 64, 104, 103, 101, 3, 0, 100,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 17, 17, 17, 17, 17, 16,
	16, 16, 16, 16, 16, 16, 15, 15, 15, 15,
	15, 15, 12, 12, 12, 10, 9, 13, 14, 8,
	8, 7, 7, 4, 4, 4, 4, 4, 4, 6,
	6, 6, 6, 6, 6, 6, 6, 5, 5, 5,
	5, 11, 11, 11, 11,
}

var yyR2 = [...]int8{
	0, 1, 1, 3, 0, 3, 3, 3, 2, 2,
	2, 4, 2, 2, 1, 1, 2, 2, 1, 2,
	1, 4, 4, 3, 4, 1, 1, 1, 3, 1,
	1, 1, 1, 1, 2, 1, 1, 1, 1, 2,
	2, 2, 2, 2, 2, 1, 1, 1, 1, 2,
	2, 2, 4, 4, 4, 2, 1, 1, 2, 2,
	3, 2, 1, 2, 1, 1, 3, 3, 2, 5,
	3, 4, 3, 1, 1, 1, 1, 2, 3, 2,
	3, 3, 5, 3, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 51, 53, 47, -9, -10, -13,
	-14, -8, 30, -7, 22, 17, 25, 24, 9, 8,
	7, 34, 36, -12, -4, -15, -17, 43, 38, 28,
	29, 6, -6, -11, 55, 12, 11, 10, 46, -16,
	16, 39, 40, 41, 42, 13, -5, 18, 19, 20,
	56, 44, 49, 48, 50, 45, -3, -3, -15, -15,
	-15, -15, 32, 16, 33, 31, 24, 23, 26, 26,
	54, 27, 5, 4, 54, 10, 46, -16, 43, 24,
	4, -11, 11, 11, 11, 21, 47, 13, 54, 14,
	11, 11, 11, 45, 53, 50, 46, 51, 52, -3,
	-3, -3, 52, 47, 31, 54, 54, -4, 54, 54,
	54, -15, 54, 21, 21, 11, 37, 11, 37, 35,
	15, -15, -4, -4, -4, -15, -15, -15, 47, 54,
	37, 37, 11,
}

var yyDef = [...]int8{
	4, -2, 1, 2, 4, 4, 0, 0, 0, 0,
	14, 15, 0, 18, 0, 20, 0, 0, 25, 26,
	27, 0, 29, 30, 31, 32, 33, 56, 57, 0,
	62, 0, 64, 65, 0, 0, 0, 46, 47, 48,
	0, 35, 36, 37, 38, 0, 73, 74, 75, 76,
	0, 0, 45, 4, 4, 4, 0, 8, 9, 10,
	12, 13, 16, 17, 58, 59, 0, 19, 0, 0,
	0, 0, 0, 0, 0, 49, 50, 51, 55, 61,
	0, 63, 0, 0, 0, 68, 0, 79, 0, 84,
	34, 77, 0, 39, 40, 41, 42, 43, 44, 3,
	5, 6, 7, 0, 60, 0, 0, 23, 0, 0,
	0, 28, 0, 66, 67, 80, 72, 81, 70, 78,
	83, 11, 21, 22, 24, 52, 53, 54, 0, 0,
	71, 69, 82,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 53, 3, 43, 3, 3, 45, 3,
	51, 52, 46, 56, 48, 55, 49, 47, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 54, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 44, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 50,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:44
		{
			yylex.(*Lexer).result = yyDollar[1].exprs
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:50
		{
			yyVAL.exprs = []Expression{yyDollar[1].expr}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:54
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lib/filter/parser.y:60
		{
			yyVAL.expr = VoidExpr{}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:64
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyDollar[1].expr, operator: '|', right: yyDollar[3].expr}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:68
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyDollar[1].expr, operator: '&', right: yyDollar[3].expr}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:72
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:76
		{
			yyVAL.expr = NotOpExpr{expr: yyDollar[2].expr}
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:80
		{
			yyVAL.expr = ProjectExpr{isAll: false, section: yyDollar[2].expr.(StringExpr).String()}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:84
		{
			yyVAL.expr = ProjectExpr{isAll: false, name: yyDollar[2].expr.(StringExpr).String()}
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:88
		{
			name := yyDollar[2].expr.(StringExpr).String()
			section := yyDollar[4].expr.(StringExpr).String()
			yyVAL.expr = ProjectExpr{isAll: false, name: name, section: section}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:94
		{
			yyVAL.expr = ProjectExpr{isAll: true, name: yyDollar[2].expr.(StringExpr).String()}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:98
		{
			yyVAL.expr = LabelExpr{name: yyDollar[2].expr.(StringExpr).String()}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:102
		{
			yyVAL.expr = LabelExpr{name: ""}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:106
		{
			yyVAL.expr = DateExpr{operation: NO_DUE_DATE}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:110
		{
			yyVAL.expr = DateExpr{operation: NO_TIME}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:114
		{
			yyVAL.expr = NoPriorityExpr{}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:118
		{
			yyVAL.expr = DateExpr{allDay: false, datetime: now(), operation: DUE_BEFORE}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:122
		{
			yyVAL.expr = ViewAllExpr{}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:126
		{
			yyVAL.expr = RecurringExpr{}
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:130
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = CREATED_BEFORE
			yyVAL.expr = e
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:136
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = DUE_BEFORE
			yyVAL.expr = e
		}
	case 23:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:142
		{
			e := yyDollar[3].expr.(DateExpr)
			e.operation = DUE_ON
			yyVAL.expr = e
		}
	case 24:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:148
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = DUE_AFTER
			yyVAL.expr = e
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:154
		{
			yyVAL.expr = SharedExpr{}
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:158
		{
			yyVAL.expr = SubtaskExpr{}
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:162
		{
			yyVAL.expr = AssignedExpr{}
		}
	case 28:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:166
		{
			yyVAL.expr = SearchExpr{keyword: yyDollar[3].expr.(StringExpr).String()}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:170
		{
			yyVAL.expr = WeekdayExpr{day: WeekdayHash[strings.ToLower(yyDollar[1].token.literal)]}
		}
	case 34:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:181
		{
			yyVAL.expr = PriorityExpr{atoi(yyDollar[2].token.literal)}
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:185
		{
			yyVAL.expr = PriorityExpr{1}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:189
		{
			yyVAL.expr = PriorityExpr{2}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:193
		{
			yyVAL.expr = PriorityExpr{3}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:197
		{
			yyVAL.expr = PriorityExpr{4}
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:203
		{
			yyVAL.expr = "&"
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:207
		{
			yyVAL.expr = "!"
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:211
		{
			yyVAL.expr = `\|`
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:215
		{
			yyVAL.expr = `\*`
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:219
		{
			yyVAL.expr = `\(`
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:223
		{
			yyVAL.expr = `\)`
		}
	case 45:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:227
		{
			yyVAL.expr = `\.`
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:233
		{
			yyVAL.expr = NewStringExpr(yyDollar[1].token.literal)
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:237
		{
			yyVAL.expr = NewStringExpr(".*")
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:241
		{
			yyVAL.expr = NewStringExpr(yyDollar[1].expr.(string))
		}
	case 49:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:245
		{
			yyVAL.expr = yyDollar[1].expr.(StringExpr).Add(NewStringExpr(yyDollar[2].token.literal))
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:249
		{
			yyVAL.expr = yyDollar[1].expr.(StringExpr).Add(NewStringExpr(".*"))
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:253
		{
			yyVAL.expr = yyDollar[1].expr.(StringExpr).Add(NewStringExpr(yyDollar[2].expr.(string)))
		}
	case 52:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:260
		{
			yyVAL.expr = PersonExpr{operation: ASSIGNED_TO, person: yyDollar[4].expr.(StringExpr).String()}
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:264
		{
			yyVAL.expr = PersonExpr{operation: ASSIGNED_BY, person: yyDollar[4].expr.(StringExpr).String()}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:268
		{
			yyVAL.expr = PersonExpr{operation: ADDED_BY, person: yyDollar[4].expr.(StringExpr).String()}
		}
	case 55:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:274
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 56:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:280
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:286
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 58:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:292
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:298
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 60:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:302
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 61:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:308
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 62:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:312
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 63:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:319
		{
			date := yyDollar[1].expr.(time.Time)
			time := yyDollar[2].expr.(time.Duration)
			yyVAL.expr = DateExpr{allDay: false, datetime: date.Add(time)}
		}
	case 64:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:325
		{
			yyVAL.expr = DateExpr{allDay: true, datetime: yyDollar[1].expr.(time.Time)}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:329
		{
			nd := now().Sub(today())
			d := yyDollar[1].expr.(time.Duration)
			if d <= nd {
				d = d + time.Duration(int64(time.Hour)*24)
			}
			yyVAL.expr = DateExpr{allDay: false, datetime: today().Add(d)}
		}
	case 66:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:338
		{
			date := today().AddDate(0, 0, -atoi(yyDollar[2].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:343
		{
			date := today().AddDate(0, 0, atoi(yyDollar[2].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 68:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:348
		{
			date := today().AddDate(0, 0, atoi(yyDollar[1].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 69:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lib/filter/parser.y:355
		{
			yyVAL.expr = time.Date(atoi(yyDollar[5].token.literal), time.Month(atoi(yyDollar[1].token.literal)), atoi(yyDollar[3].token.literal), 0, 0, 0, 0, timezone())
		}
	case 70:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:359
		{
			yyVAL.expr = time.Date(atoi(yyDollar[3].token.literal), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 71:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:363
		{
			yyVAL.expr = time.Date(atoi(yyDollar[4].token.literal), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 72:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:367
		{
			yyVAL.expr = time.Date(atoi(yyDollar[3].token.literal), MonthIdentHash[strings.ToLower(yyDollar[2].token.literal)], atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 73:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:371
		{
			tod := today()
			date := yyDollar[1].expr.(time.Time)
			if date.Before(tod) {
				date = date.AddDate(1, 0, 0)
			}
			yyVAL.expr = date
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:380
		{
			yyVAL.expr = today()
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:384
		{
			yyVAL.expr = today().AddDate(0, 0, 1)
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:388
		{
			yyVAL.expr = today().AddDate(0, 0, -1)
		}
	case 77:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:394
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 78:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:398
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 79:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:402
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[2].token.literal)], atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 80:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:406
		{
			yyVAL.expr = time.Date(now().Year(), time.Month(atoi(yyDollar[3].token.literal)), atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:412
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyDollar[1].token.literal)) + int64(time.Minute)*int64(atoi(yyDollar[3].token.literal)))
		}
	case 82:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lib/filter/parser.y:416
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyDollar[1].token.literal)) + int64(time.Minute)*int64(atoi(yyDollar[3].token.literal)) + int64(time.Second)*int64(atoi(yyDollar[5].token.literal)))
		}
	case 83:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:420
		{
			yyVAL.expr = time.Duration(int64(time.Hour) * int64(atoi(yyDollar[2].token.literal)))
		}
	case 84:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:424
		{
			hour := atoi(yyDollar[1].token.literal)
			if TwelveClockIdentHash[yyDollar[2].token.literal] {
				hour = hour + 12
			}
			yyVAL.expr = time.Duration(int64(time.Hour) * int64(hour))
		}
	}
	goto yystack /* stack new state and value */
}
