// Code generated by goyacc -o lib/filter/parser.go lib/filter/parser.y. DO NOT EDIT.

//line lib/filter/parser.y:2
package filter

import __yyfmt__ "fmt"

//line lib/filter/parser.y:2

import (
	"strings"
	"time"
)

//line lib/filter/parser.y:9
type yySymType struct {
	yys   int
	token Token
	expr  Expression
	exprs []Expression
}

const BY = 57346
const TO = 57347
const ADDED = 57348
const ASSIGNED = 57349
const SUBTASK = 57350
const SHARED = 57351
const STRING = 57352
const NUMBER = 57353
const NEXT = 57354
const MONTH_IDENT = 57355
const TWELVE_CLOCK_IDENT = 57356
const MINUTES = 57357
const HOURS = 57358
const PRIORITY = 57359
const RECURRING = 57360
const TODAY_IDENT = 57361
const TOMORROW_IDENT = 57362
const YESTERDAY_IDENT = 57363
const DAYS = 57364
const VIEW = 57365
const ALL = 57366
const DUE = 57367
const CREATED = 57368
const BEFORE = 57369
const AFTER = 57370
const OVER = 57371
const OVERDUE = 57372
const NO = 57373
const DATE = 57374
const TIME = 57375
const LABELS = 57376
const SEARCH = 57377
const ORDINAL = 57378
const WEEKDAY = 57379
const YEAR_NUMBER = 57380
const AT = 57381
const P1 = 57382
const P2 = 57383
const P3 = 57384
const P4 = 57385

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"BY",
	"TO",
	"ADDED",
	"ASSIGNED",
	"SUBTASK",
	"SHARED",
	"STRING",
	"NUMBER",
	"NEXT",
	"MONTH_IDENT",
	"TWELVE_CLOCK_IDENT",
	"MINUTES",
	"HOURS",
	"PRIORITY",
	"RECURRING",
	"TODAY_IDENT",
	"TOMORROW_IDENT",
	"YESTERDAY_IDENT",
	"DAYS",
	"VIEW",
	"ALL",
	"DUE",
	"CREATED",
	"BEFORE",
	"AFTER",
	"OVER",
	"OVERDUE",
	"NO",
	"DATE",
	"TIME",
	"LABELS",
	"SEARCH",
	"ORDINAL",
	"WEEKDAY",
	"YEAR_NUMBER",
	"AT",
	"P1",
	"P2",
	"P3",
	"P4",
	"'#'",
	"'\\\\'",
	"'&'",
	"'*'",
	"'/'",
	"','",
	"'.'",
	"'|'",
	"'('",
	"')'",
	"'!'",
	"':'",
	"'-'",
	"'+'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line lib/filter/parser.y:446

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 186

var yyAct = [...]uint8{
	39, 83, 24, 25, 134, 114, 36, 35, 45, 112,
	58, 59, 60, 61, 47, 48, 49, 3, 70, 72,
	111, 110, 56, 57, 94, 97, 78, 108, 90, 96,
	98, 99, 95, 88, 90, 107, 106, 75, 55, 55,
	79, 76, 86, 54, 54, 103, 71, 50, 76, 53,
	133, 34, 50, 121, 37, 120, 136, 135, 105, 78,
	78, 78, 78, 118, 69, 68, 80, 33, 87, 89,
	67, 100, 101, 102, 109, 89, 51, 116, 77, 113,
	115, 52, 63, 51, 137, 77, 104, 119, 52, 51,
	66, 38, 117, 93, 52, 124, 123, 65, 62, 64,
	82, 92, 122, 91, 85, 84, 74, 73, 125, 126,
	127, 128, 81, 129, 78, 130, 131, 26, 132, 10,
	9, 23, 8, 7, 11, 13, 78, 32, 46, 2,
	1, 78, 78, 78, 31, 20, 19, 18, 37, 36,
	35, 45, 0, 0, 0, 40, 15, 47, 48, 49,
	0, 14, 0, 17, 16, 0, 0, 29, 30, 12,
	0, 0, 0, 21, 0, 22, 0, 28, 41, 42,
	43, 44, 27, 51, 0, 38, 6, 0, 52, 0,
	4, 0, 5, 0, 34, 50,
}

var yyPact = [...]int16{
	128, -1000, 0, -7, 128, 128, 44, 44, 44, 44,
	-1000, -1000, 65, -1000, 46, -1000, 37, -9, -1000, -1000,
	102, -18, -1000, -1000, -1000, 31, -1000, -4, -1000, 41,
	-1000, 108, -10, -1000, 94, 93, 20, -1000, -1000, -1000,
	92, -1000, -1000, -1000, -1000, 90, -1000, -1000, -1000, -1000,
	82, -22, -1000, 128, 128, 128, -8, -1000, 31, 38,
	31, 31, -1000, -1000, -1000, -1000, 26, -1000, -19, -20,
	-28, -5, -34, -35, -46, 44, -1000, -1000, -1000, -1000,
	-1000, -50, -1000, 14, 58, 55, -1000, 81, 25, 76,
	-1000, -1000, 17, 80, -1000, -1000, -1000, -1000, -1000, -1000,
	-7, -1000, -1000, -1000, 44, -1000, -5, -5, -5, -1000,
	-5, 44, 44, 31, 44, -1000, -1000, 2, -1000, -51,
	-1000, 19, -1000, -1000, -1000, 31, -1000, -1000, -1000, -1000,
	31, 31, 31, 18, 73, -1000, -1000, -1000,
}

var yyPgo = [...]uint8{
	0, 130, 129, 17, 2, 128, 127, 125, 124, 123,
	122, 67, 121, 120, 119, 3, 0, 117,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 17, 17, 17, 17, 17,
	16, 16, 16, 16, 16, 16, 16, 15, 15, 15,
	15, 15, 15, 12, 12, 12, 10, 9, 13, 14,
	8, 8, 7, 7, 4, 4, 4, 4, 4, 4,
	6, 6, 6, 6, 6, 6, 6, 6, 5, 5,
	5, 5, 11, 11, 11, 11, 11, 11,
}

var yyR2 = [...]int8{
	0, 1, 1, 3, 0, 3, 3, 3, 2, 2,
	2, 4, 2, 2, 1, 1, 2, 2, 1, 2,
	1, 4, 4, 4, 3, 4, 1, 1, 1, 3,
	1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
	2, 2, 2, 2, 2, 2, 1, 1, 1, 1,
	2, 2, 2, 4, 4, 4, 2, 1, 1, 2,
	2, 3, 2, 1, 2, 1, 1, 3, 3, 2,
	5, 3, 4, 3, 1, 1, 1, 1, 2, 3,
	2, 3, 3, 5, 3, 3, 3, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 52, 54, 48, -9, -10, -13,
	-14, -8, 31, -7, 23, 18, 26, 25, 9, 8,
	7, 35, 37, -12, -4, -15, -17, 44, 39, 29,
	30, 6, -6, -11, 56, 12, 11, 10, 47, -16,
	17, 40, 41, 42, 43, 13, -5, 19, 20, 21,
	57, 45, 50, 49, 51, 46, -3, -3, -15, -15,
	-15, -15, 33, 17, 34, 32, 25, 24, 28, 27,
	27, 55, 28, 5, 4, 55, 10, 47, -16, 44,
	25, 4, -11, 11, 11, 11, 22, 48, 13, 55,
	14, 11, 11, 11, 46, 54, 51, 47, 52, 53,
	-3, -3, -3, 53, 48, 32, 55, 55, 55, -4,
	55, 55, 55, -15, 55, 22, 22, 11, 38, 11,
	38, 36, 22, 16, 15, -15, -4, -4, -4, -4,
	-15, -15, -15, 48, 55, 38, 38, 11,
}

var yyDef = [...]int8{
	4, -2, 1, 2, 4, 4, 0, 0, 0, 0,
	14, 15, 0, 18, 0, 20, 0, 0, 26, 27,
	28, 0, 30, 31, 32, 33, 34, 57, 58, 0,
	63, 0, 65, 66, 0, 0, 0, 47, 48, 49,
	0, 36, 37, 38, 39, 0, 74, 75, 76, 77,
	0, 0, 46, 4, 4, 4, 0, 8, 9, 10,
	12, 13, 16, 17, 59, 60, 0, 19, 0, 0,
	0, 0, 0, 0, 0, 0, 50, 51, 52, 56,
	62, 0, 64, 0, 0, 0, 69, 0, 80, 0,
	87, 35, 78, 0, 40, 41, 42, 43, 44, 45,
	3, 5, 6, 7, 0, 61, 0, 0, 0, 24,
	0, 0, 0, 29, 0, 67, 68, 81, 73, 82,
	71, 79, 84, 85, 86, 11, 21, 22, 23, 25,
	53, 54, 55, 0, 0, 72, 70, 83,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 54, 3, 44, 3, 3, 46, 3,
	52, 53, 47, 57, 49, 56, 50, 48, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 55, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 45, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 51,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:44
		{
			yylex.(*Lexer).result = yyDollar[1].exprs
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:50
		{
			yyVAL.exprs = []Expression{yyDollar[1].expr}
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:54
		{
			yyVAL.exprs = append(yyDollar[1].exprs, yyDollar[3].expr)
		}
	case 4:
		yyDollar = yyS[yypt-0 : yypt+1]
//line lib/filter/parser.y:60
		{
			yyVAL.expr = VoidExpr{}
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:64
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyDollar[1].expr, operator: '|', right: yyDollar[3].expr}
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:68
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyDollar[1].expr, operator: '&', right: yyDollar[3].expr}
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:72
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:76
		{
			yyVAL.expr = NotOpExpr{expr: yyDollar[2].expr}
		}
	case 9:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:80
		{
			yyVAL.expr = ProjectExpr{isAll: false, section: yyDollar[2].expr.(StringExpr).String()}
		}
	case 10:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:84
		{
			yyVAL.expr = ProjectExpr{isAll: false, name: yyDollar[2].expr.(StringExpr).String()}
		}
	case 11:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:88
		{
			name := yyDollar[2].expr.(StringExpr).String()
			section := yyDollar[4].expr.(StringExpr).String()
			yyVAL.expr = ProjectExpr{isAll: false, name: name, section: section}
		}
	case 12:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:94
		{
			yyVAL.expr = ProjectExpr{isAll: true, name: yyDollar[2].expr.(StringExpr).String()}
		}
	case 13:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:98
		{
			yyVAL.expr = LabelExpr{name: yyDollar[2].expr.(StringExpr).String()}
		}
	case 14:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:102
		{
			yyVAL.expr = LabelExpr{name: ""}
		}
	case 15:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:106
		{
			yyVAL.expr = DateExpr{operation: NO_DUE_DATE}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:110
		{
			yyVAL.expr = DateExpr{operation: NO_TIME}
		}
	case 17:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:114
		{
			yyVAL.expr = NoPriorityExpr{}
		}
	case 18:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:118
		{
			yyVAL.expr = DateExpr{allDay: false, datetime: now(), operation: DUE_BEFORE}
		}
	case 19:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:122
		{
			yyVAL.expr = ViewAllExpr{}
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:126
		{
			yyVAL.expr = RecurringExpr{}
		}
	case 21:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:130
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = CREATED_AFTER
			yyVAL.expr = e
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:136
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = CREATED_BEFORE
			yyVAL.expr = e
		}
	case 23:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:142
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = DUE_BEFORE
			yyVAL.expr = e
		}
	case 24:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:148
		{
			e := yyDollar[3].expr.(DateExpr)
			e.operation = DUE_ON
			yyVAL.expr = e
		}
	case 25:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:154
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = DUE_AFTER
			yyVAL.expr = e
		}
	case 26:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:160
		{
			yyVAL.expr = SharedExpr{}
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:164
		{
			yyVAL.expr = SubtaskExpr{}
		}
	case 28:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:168
		{
			yyVAL.expr = AssignedExpr{}
		}
	case 29:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:172
		{
			yyVAL.expr = SearchExpr{keyword: yyDollar[3].expr.(StringExpr).String()}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:176
		{
			yyVAL.expr = WeekdayExpr{day: WeekdayHash[strings.ToLower(yyDollar[1].token.literal)]}
		}
	case 35:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:187
		{
			yyVAL.expr = PriorityExpr{atoi(yyDollar[2].token.literal)}
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:191
		{
			yyVAL.expr = PriorityExpr{1}
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:195
		{
			yyVAL.expr = PriorityExpr{2}
		}
	case 38:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:199
		{
			yyVAL.expr = PriorityExpr{3}
		}
	case 39:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:203
		{
			yyVAL.expr = PriorityExpr{4}
		}
	case 40:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:209
		{
			yyVAL.expr = "&"
		}
	case 41:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:213
		{
			yyVAL.expr = "!"
		}
	case 42:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:217
		{
			yyVAL.expr = `\|`
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:221
		{
			yyVAL.expr = `\*`
		}
	case 44:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:225
		{
			yyVAL.expr = `\(`
		}
	case 45:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:229
		{
			yyVAL.expr = `\)`
		}
	case 46:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:233
		{
			yyVAL.expr = `\.`
		}
	case 47:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:239
		{
			yyVAL.expr = NewStringExpr(yyDollar[1].token.literal)
		}
	case 48:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:243
		{
			yyVAL.expr = NewStringExpr(".*")
		}
	case 49:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:247
		{
			yyVAL.expr = NewStringExpr(yyDollar[1].expr.(string))
		}
	case 50:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:251
		{
			yyVAL.expr = yyDollar[1].expr.(StringExpr).Add(NewStringExpr(yyDollar[2].token.literal))
		}
	case 51:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:255
		{
			yyVAL.expr = yyDollar[1].expr.(StringExpr).Add(NewStringExpr(".*"))
		}
	case 52:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:259
		{
			yyVAL.expr = yyDollar[1].expr.(StringExpr).Add(NewStringExpr(yyDollar[2].expr.(string)))
		}
	case 53:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:266
		{
			yyVAL.expr = PersonExpr{operation: ASSIGNED_TO, person: yyDollar[4].expr.(StringExpr).String()}
		}
	case 54:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:270
		{
			yyVAL.expr = PersonExpr{operation: ASSIGNED_BY, person: yyDollar[4].expr.(StringExpr).String()}
		}
	case 55:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:274
		{
			yyVAL.expr = PersonExpr{operation: ADDED_BY, person: yyDollar[4].expr.(StringExpr).String()}
		}
	case 56:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:280
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 57:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:286
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 58:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:292
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 59:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:298
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 60:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:304
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 61:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:308
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 62:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:314
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 63:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:318
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 64:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:325
		{
			date := yyDollar[1].expr.(time.Time)
			time := yyDollar[2].expr.(time.Duration)
			yyVAL.expr = DateExpr{allDay: false, datetime: date.Add(time)}
		}
	case 65:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:331
		{
			yyVAL.expr = DateExpr{allDay: true, datetime: yyDollar[1].expr.(time.Time)}
		}
	case 66:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:335
		{
			nd := now().Sub(today())
			d := yyDollar[1].expr.(time.Duration)
			if d <= nd {
				d = d + time.Duration(int64(time.Hour)*24)
			}
			yyVAL.expr = DateExpr{allDay: false, datetime: today().Add(d)}
		}
	case 67:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:344
		{
			date := today().AddDate(0, 0, -atoi(yyDollar[2].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 68:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:349
		{
			date := today().AddDate(0, 0, atoi(yyDollar[2].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 69:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:354
		{
			date := today().AddDate(0, 0, atoi(yyDollar[1].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 70:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lib/filter/parser.y:361
		{
			yyVAL.expr = time.Date(atoi(yyDollar[5].token.literal), time.Month(atoi(yyDollar[1].token.literal)), atoi(yyDollar[3].token.literal), 0, 0, 0, 0, timezone())
		}
	case 71:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:365
		{
			yyVAL.expr = time.Date(atoi(yyDollar[3].token.literal), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 72:
		yyDollar = yyS[yypt-4 : yypt+1]
//line lib/filter/parser.y:369
		{
			yyVAL.expr = time.Date(atoi(yyDollar[4].token.literal), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 73:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:373
		{
			yyVAL.expr = time.Date(atoi(yyDollar[3].token.literal), MonthIdentHash[strings.ToLower(yyDollar[2].token.literal)], atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 74:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:377
		{
			tod := today()
			date := yyDollar[1].expr.(time.Time)
			if date.Before(tod) {
				date = date.AddDate(1, 0, 0)
			}
			yyVAL.expr = date
		}
	case 75:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:386
		{
			yyVAL.expr = today()
		}
	case 76:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:390
		{
			yyVAL.expr = today().AddDate(0, 0, 1)
		}
	case 77:
		yyDollar = yyS[yypt-1 : yypt+1]
//line lib/filter/parser.y:394
		{
			yyVAL.expr = today().AddDate(0, 0, -1)
		}
	case 78:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:400
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 79:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:404
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 80:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:408
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[2].token.literal)], atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 81:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:412
		{
			yyVAL.expr = time.Date(now().Year(), time.Month(atoi(yyDollar[3].token.literal)), atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 82:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:418
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyDollar[1].token.literal)) + int64(time.Minute)*int64(atoi(yyDollar[3].token.literal)))
		}
	case 83:
		yyDollar = yyS[yypt-5 : yypt+1]
//line lib/filter/parser.y:422
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyDollar[1].token.literal)) + int64(time.Minute)*int64(atoi(yyDollar[3].token.literal)) + int64(time.Second)*int64(atoi(yyDollar[5].token.literal)))
		}
	case 84:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:426
		{
			yyVAL.expr = time.Duration(int64(time.Hour) * int64(atoi(yyDollar[2].token.literal)) * 24)
		}
	case 85:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:430
		{
			yyVAL.expr = nowDuration() + time.Duration(int64(time.Hour)*int64(atoi(yyDollar[2].token.literal)))
		}
	case 86:
		yyDollar = yyS[yypt-3 : yypt+1]
//line lib/filter/parser.y:434
		{
			yyVAL.expr = nowDuration() + time.Duration(int64(time.Minute)*int64(atoi(yyDollar[2].token.literal)))
		}
	case 87:
		yyDollar = yyS[yypt-2 : yypt+1]
//line lib/filter/parser.y:438
		{
			hour := atoi(yyDollar[1].token.literal)
			if TwelveClockIdentHash[yyDollar[2].token.literal] {
				hour = hour + 12
			}
			yyVAL.expr = time.Duration(int64(time.Hour) * int64(hour))
		}
	}
	goto yystack /* stack new state and value */
}
